### ISSUE TITLE
No sound, no controls

### ISSUE THREAD

**Issue by Localhorst86** [lantus/cannonball-nx#4]
I am trying to run this on my 5.0.2 switch. I placed the roms from the Outrun revision b set into the roms folder. canonball starts up and I can see the game running, I don't - however - get any sound and no inputs are working.

I double and tripple checked that all my files are named correctly according to the readme.

**Comment by lantus** [comment]
press the left thumbstick to insert a coin, then press 'Y' to start a game

**Comment by Localhorst86** [comment]
That's it. I am officially stupid. I didn't realize the sticks on the switch can be clicked...

**Comment by lantus** [comment]
no worries - enjoy :)
